version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run app rails db:migrate
      - run:
          name: Rubocop
          command: docker-compose run app bundle exec rubocop
      - run:
          name: Rspec
          command: docker-compose run app rbundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down